[ARO-6013] Release 4.12 Hacks
openshift/installer-aro pull request #32
Opened 2024-07-11 14:29 UTC by mrWinston

Rebase ARO Hacks on top of the latest release-4.12 branch from the openshift-installer repo.

This PR adds a single commit on top of that to fix the go.mod file. I'm unsure if that's the way things should be done or if there was something going weird during rebasing/cherry-picking. 

- Jira: https://issues.redhat.com/browse/ARO-6013

2024-07-11 14:40 UTC, mrWinston commented
The tests seem to be failing because of the merge conflicts. Is that important? IT will need to be force-pushed anyway as the branch has been rebased.

2024-07-12 10:46 UTC, tiguelu commented
> The tests seem to be failing because of the merge conflicts. Is that important? IT will need to be force-pushed anyway as the branch has been rebased.

Correct, they are not going to work in the fork because of the merge conflict. The code is imported as a library in the wrapper where we don't have this problem, so the image will be indirectly tested there.

2024-07-12 15:48 UTC, tiguelu requested changes

2024-07-12 15:48 UTC, tiguelu commented on data/assets_vfsdata.go
> +			compressedContent: []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x54\xbd\x8e\xdb\x30\x0c\xde\xfd\x14\x44\xa6\x76\xb9\xa9\xeb\x6d\x5d\x3
The content of rhcos.json is the same as in the existing branch, but it should be different. 

The [instructions](https://github.com/openshift/installer-aro-wrapper/blob/main/docs/upstream-differences.md#update-installer-fork-again) need to be updated as they are not including the step to update the generated assets.

We'll be changing this next week.

2024-07-19 14:21 UTC, tiguelu requested changes
Minor change in OWNERS file.

2024-07-19 14:21 UTC, tiguelu commented on OWNERS
>  reviewers:
Some people have left the team since this patch was first created. Can you amend and re-push this last commit to remove these users please?
dofinn
s-amann
shivkumar13

2024-07-22 13:57 UTC, mrWinston commented on OWNERS
>  reviewers:
Done!

2024-07-24 09:48 UTC, bitoku approved these changes

2024-07-24 14:45 UTC, tiguelu commented
/approve

2024-07-24 14:46 UTC, tiguelu approved these changes

2024-07-24 14:55 UTC, merged